export const scholarships = [
  // --- National Scholarship Portal (NSP) ---
  {
    title: "Central Sector Scheme of Scholarship for College and University Students",
    provider: "National Scholarship Portal (NSP) - Ministry of Education, Govt of India",
    amount: "₹12,000 to ₹20,000 per year",
    deadline: new Date("2026-10-31"),
    states: ["All India"],
    courses: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    incomeLimit: 450000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Class 12th Marksheet", "Income Certificate", "Aadhaar Card", "Bank Passbook"],
    description: "Supports meritorious students from families with an annual income below ₹4.5L who are in the top 20th percentile of their state boards.",
    featured: true,
    tags: ["NSP", "Government", "Merit"]
  },
  {
    title: "Post-Matric Scholarship for Students belonging to Minority Communities",
    provider: "National Scholarship Portal (NSP) - Ministry of Minority Affairs",
    amount: "₹6,000 to ₹15,000 per year",
    deadline: new Date("2026-11-15"),
    states: ["All India"],
    courses: ["UG", "PG", "Diploma", "PhD"],
    categories: ["Minority"],
    incomeLimit: 200000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year", "4th Year"],
    requiredDocuments: ["Minority Certificate", "Income Certificate", "Previous Marksheet", "Fee Receipt"],
    description: "Financial assistance for meritorious students belonging to Muslim, Christian, Sikh, Buddhist, Jain, or Parsi communities.",
    featured: false,
    tags: ["NSP", "Minority", "Government"]
  },
  {
    title: "PM YASHASVI Central Sector Scheme of Top Class Education",
    provider: "National Scholarship Portal (NSP) - Ministry of Social Justice and Empowerment",
    amount: "₹75,000 to ₹1,25,000 per year",
    deadline: new Date("2026-11-30"),
    states: ["All India"],
    courses: ["UG", "10+2"],
    categories: ["OBC", "EBC", "DNT"],
    incomeLimit: 250000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Caste Certificate", "Income Certificate", "School ID Card", "Aadhaar Card"],
    description: "Top class education scholarship for OBC, EBC and DNT students studying in identified premium schools and colleges.",
    featured: true,
    tags: ["NSP", "OBC", "Government"]
  },
  {
    title: "Pragati Scholarship Scheme for Girl Students for Technical Degree",
    provider: "AICTE - Government of India",
    amount: "₹50,000 per year",
    deadline: new Date("2026-10-15"),
    states: ["All India"],
    courses: ["UG", "Diploma"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 800000,
    yearLevels: ["1st Year", "2nd Year"],
    requiredDocuments: ["Admission Letter", "Income Certificate", "Aadhaar Card", "Tuition Fee Receipt"],
    description: "Encourages and supports girl students pursuing technical education (B.Tech, B.Arch, B.Pharm) at AICTE-approved institutions.",
    featured: true,
    tags: ["AICTE", "Girl Student", "Technical"]
  },
  {
    title: "Saksham Scholarship Scheme for Specially Abled Students for Technical Degree",
    provider: "AICTE - Government of India",
    amount: "₹50,000 per year",
    deadline: new Date("2026-10-15"),
    states: ["All India"],
    courses: ["UG", "Diploma"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 800000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Disability Certificate (40%+)", "Admission Letter", "Income Certificate", "Aadhaar"],
    description: "Supports specially-abled students who are pursuing technical education in AICTE approved colleges.",
    featured: false,
    tags: ["AICTE", "Differently Abled", "Government"]
  },
  {
    title: "Kishore Vaigyanik Protsahan Yojana (KVPY)",
    provider: "Department of Science and Technology, Govt of India",
    amount: "₹5,000 to ₹7,000 per month + Contingency",
    deadline: new Date("2026-08-30"),
    states: ["All India"],
    courses: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 1000000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["KVPY Admit Card", "Marksheet", "Category Certificate", "College ID"],
    description: "National fellowship program in Basic Sciences to encourage students to take up research careers.",
    featured: true,
    tags: ["Science", "Research", "Fellowship"]
  },
  
  // --- State Scholarship Portals ---
  // Bihar
  {
    title: "Bihar Post Matric Scholarship (PMS) for OBC/EBC",
    provider: "Education Department, Government of Bihar",
    amount: "₹2,000 to ₹15,000 per year",
    deadline: new Date("2026-09-30"),
    states: ["Bihar"],
    courses: ["10+2", "UG", "PG", "Diploma"],
    categories: ["OBC", "EBC"],
    incomeLimit: 300000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year", "4th Year"],
    requiredDocuments: ["Bihar Residential Certificate", "Caste Certificate", "Income Certificate", "Bonafide Certificate"],
    description: "Provides financial aid to post-matric students of Backward Class (BC) and Extremely Backward Class (EBC) in Bihar.",
    featured: true,
    tags: ["Bihar", "State", "Post-Matric"]
  },
  {
    title: "Bihar Post Matric Scholarship (PMS) for SC/ST",
    provider: "Education Department, Government of Bihar",
    amount: "₹3,000 to ₹25,000 per year",
    deadline: new Date("2026-09-30"),
    states: ["Bihar"],
    courses: ["10+2", "UG", "PG", "Diploma"],
    categories: ["SC", "ST"],
    incomeLimit: 250000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year", "4th Year"],
    requiredDocuments: ["Residential Certificate", "Caste Certificate", "Income Certificate", "Marksheet"],
    description: "Dedicated scholarship scheme to fund education for Scheduled Caste and Scheduled Tribe students native to Bihar.",
    featured: false,
    tags: ["Bihar", "State", "SC/ST"]
  },
  {
    title: "Mukhyamantri Kanya Utthan Yojana (Graduation)",
    provider: "Government of Bihar",
    amount: "₹50,000 one-time",
    deadline: new Date("2026-12-15"),
    states: ["Bihar"],
    courses: ["UG"],
    categories: ["General", "OBC", "SC", "ST", "EBC"],
    incomeLimit: 9999999, // No limit explicitly mentioned for graduation
    yearLevels: ["Final Year"],
    requiredDocuments: ["Graduation Marksheet", "Residential Certificate", "Bank Passbook Linkage", "Aadhaar Card"],
    description: "Incentive scheme for female students of Bihar who complete graduation from recognized state universities.",
    featured: true,
    tags: ["Bihar", "Girl Student", "Incentive"]
  },
  {
    title: "Mukhyamantri Balak/Balika Protsahan Yojana (10th Pass)",
    provider: "Government of Bihar",
    amount: "₹10,000 one-time",
    deadline: new Date("2026-08-15"),
    states: ["Bihar"],
    courses: ["10+2"],
    categories: ["General", "OBC", "SC", "ST", "EBC"],
    incomeLimit: 150000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Class 10th Marksheet", "Registration Number", "Aadhaar Card", "Bank Account Details"],
    description: "Financial encouragement for students passing the Bihar Board 10th exams with 1st division.",
    featured: false,
    tags: ["Bihar", "School", "Incentive"]
  },
  // Uttar Pradesh
  {
    title: "UP Post Matric Scholarship for General/OBC/Minority",
    provider: "Social Welfare Department, Govt of Uttar Pradesh",
    amount: "Fee reimbursement + stipend",
    deadline: new Date("2026-11-10"),
    states: ["Uttar Pradesh"],
    courses: ["UG", "PG", "Diploma"],
    categories: ["General", "OBC", "Minority"],
    incomeLimit: 200000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year", "4th Year"],
    requiredDocuments: ["Domicile Certificate", "Caste Certificate", "Income Certificate", "Fee Receipt", "Aadhaar"],
    description: "Reimbursement of tuition fees and monthly allowances for students studying in UP colleges.",
    featured: true,
    tags: ["UP", "State", "Fee Reimbursement"]
  },
  {
    title: "UP Post Matric Scholarship for SC/ST",
    provider: "Social Welfare Department, Govt of Uttar Pradesh",
    amount: "Complete fee reimbursement",
    deadline: new Date("2026-11-20"),
    states: ["Uttar Pradesh"],
    courses: ["UG", "PG", "Diploma"],
    categories: ["SC", "ST"],
    incomeLimit: 250000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year", "4th Year"],
    requiredDocuments: ["Domicile Certificate", "Caste Certificate", "Income Certificate", "College ID", "Fee Receipt"],
    description: "Full scholarship and fee reimbursement program for SC/ST students enrolled in registered educational institutions in UP.",
    featured: false,
    tags: ["UP", "State", "SC/ST"]
  },
  // West Bengal
  {
    title: "Swami Vivekananda Merit-cum-Means Scholarship (SVMCM)",
    provider: "Government of West Bengal",
    amount: "₹12,000 to ₹60,000 per year",
    deadline: new Date("2026-11-30"),
    states: ["West Bengal"],
    courses: ["10+2", "UG", "PG", "Diploma", "PhD"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 250000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["WB Domicile Proof", "Previous Exam Marksheet", "Income Certificate", "Admission Receipt"],
    description: "Assists meritorious students who are residents of West Bengal and are pursuing higher studies within the state.",
    featured: true,
    tags: ["West Bengal", "State", "Merit"]
  },
  {
    title: "Oasis Post-Matric Scholarship",
    provider: "Backward Classes Welfare Department, Govt of West Bengal",
    amount: "Up to ₹12,000 per year",
    deadline: new Date("2026-10-31"),
    states: ["West Bengal"],
    courses: ["UG", "PG", "Diploma"],
    categories: ["SC", "ST", "OBC"],
    incomeLimit: 250000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year"],
    requiredDocuments: ["Caste Certificate", "Income Proof", "Previous Marksheet", "Aadhaar Card"],
    description: "Dedicated post-matric scholarship scheme for SC, ST, and OBC students residing in West Bengal.",
    featured: false,
    tags: ["West Bengal", "State", "SC/ST/OBC"]
  },
  // Maharashtra
  {
    title: "Rajarshi Chhatrapati Shahu Maharaj Fee Reimbursement Scheme",
    provider: "DTE, Government of Maharashtra",
    amount: "50% to 100% Tuition Fee Waiver",
    deadline: new Date("2026-10-15"),
    states: ["Maharashtra"],
    courses: ["UG", "PG", "Diploma"],
    categories: ["General", "EWS"],
    incomeLimit: 800000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year", "4th Year"],
    requiredDocuments: ["Maharashtra Domicile", "Income Certificate", "CAP Round Admission Letter", "Marksheet"],
    description: "Financial assistance for open-category and EWS students of Maharashtra enrolled in professional courses.",
    featured: true,
    tags: ["Maharashtra", "State", "Fee Waiver"]
  },
  {
    title: "MahaDBT Post-Matric Scholarship (SC/ST/OBC/SBC)",
    provider: "Social Justice and Special Assistance, Govt of Maharashtra",
    amount: "Tuition fee waiver + hostel maintenance allowance",
    deadline: new Date("2026-11-15"),
    states: ["Maharashtra"],
    courses: ["10+2", "UG", "PG", "Diploma"],
    categories: ["SC", "ST", "OBC"],
    incomeLimit: 450000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year"],
    requiredDocuments: ["Caste Certificate", "Income Proof", "Aadhar Linked Bank Account", "Domicile Certificate"],
    description: "Maharashtra state portal scholarship for backward classes seeking higher education.",
    featured: false,
    tags: ["Maharashtra", "State", "MahaDBT"]
  },
  // Karnataka
  {
    title: "SSP Post-Matric Scholarship Karnataka",
    provider: "State Scholarship Portal (SSP), Govt of Karnataka",
    amount: "₹5,000 to ₹30,000 per year",
    deadline: new Date("2026-10-30"),
    states: ["Karnataka"],
    courses: ["UG", "PG", "Diploma"],
    categories: ["SC", "ST", "OBC", "Minority"],
    incomeLimit: 250000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year", "4th Year"],
    requiredDocuments: ["SSP ID", "Caste/Income RD Number", "College Admission Details", "Aadhar Consent Form"],
    description: "Integrated state scholarship portal for multiple departments in Karnataka assisting backward classes.",
    featured: true,
    tags: ["Karnataka", "State", "SSP"]
  },
  // Delhi
  {
    title: "Delhi Ladli Scheme Scholarship",
    provider: "Department of Women and Child Development, Govt of Delhi",
    amount: "₹5,000 to ₹10,000 per year",
    deadline: new Date("2026-09-15"),
    states: ["Delhi"],
    courses: ["10+2"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 100000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Delhi Domicile/Residence proof", "Birth Certificate", "Income Affidavit", "School Report Card"],
    description: "Encourages the education of girl students in Delhi schools to prevent dropout rates.",
    featured: false,
    tags: ["Delhi", "State", "Girl Student"]
  },

  // --- Banking & Corporate Scholarships ---
  {
    title: "HDFC Bank Parivartan's ECS Scholarship",
    provider: "HDFC Bank",
    amount: "₹30,000 to ₹75,000 per year",
    deadline: new Date("2026-09-30"),
    states: ["All India"],
    courses: ["10+2", "UG", "PG", "Diploma"],
    categories: ["General", "OBC", "SC", "ST", "EWS"],
    incomeLimit: 250000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year", "4th Year"],
    requiredDocuments: ["Previous Year Marksheet", "Income Proof", "Current Admission Letter", "HDFC Form"],
    description: "Scholarship aimed at helping students facing personal or financial crises to continue their education.",
    featured: true,
    tags: ["HDFC", "Banking", "Private"]
  },
  {
    title: "SBI Asha Scholarship Program",
    provider: "SBI Foundation",
    amount: "₹15,000 per year",
    deadline: new Date("2026-08-31"),
    states: ["All India"],
    courses: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 300000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Marksheet (Min 75% in Class 12)", "Income Certificate", "College Fee Bill", "Aadhaar Card"],
    description: "Aims to support the higher education of meritorious students from socio-economically weak backgrounds.",
    featured: true,
    tags: ["SBI", "Banking", "Merit"]
  },
  {
    title: "Kotak Kanya Scholarship",
    provider: "Kotak Education Foundation",
    amount: "₹1,50,000 per year",
    deadline: new Date("2026-09-15"),
    states: ["All India"],
    courses: ["UG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 320000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Class 12 Marksheet", "College Admission Proof", "Parent's Income Document", "Photos"],
    description: "Financial assistance for meritorious girl students to pursue professional graduation courses (Engineering, Medical, Law, Architecture).",
    featured: true,
    tags: ["Kotak", "Banking", "Girl Student"]
  },
  {
    title: "LIC Golden Jubilee Scholarship Scheme",
    provider: "Life Insurance Corporation of India (LIC)",
    amount: "₹20,000 per year",
    deadline: new Date("2026-12-10"),
    states: ["All India"],
    courses: ["UG", "PG", "Diploma"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 250000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Class 12 Certificate", "Income Certificate", "Caste Certificate", "Bank Account Details"],
    description: "Supports students from economically weaker sections pursuing studies in government or private colleges.",
    featured: false,
    tags: ["LIC", "Corporate", "Financial-Aid"]
  },
  {
    title: "Tata Million Minds Scholarship",
    provider: "Tata Capital Ltd",
    amount: "Up to ₹50,000",
    deadline: new Date("2026-10-31"),
    states: ["All India"],
    courses: ["UG", "PG", "Diploma"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 400000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year"],
    requiredDocuments: ["Previous Marksheet", "Income proof", "Institution ID Card", "Bank Details"],
    description: "Assists students pursuing professional degrees or diplomas in Indian colleges.",
    featured: false,
    tags: ["Tata", "Corporate", "Private"]
  },
  {
    title: "Reliance Foundation Undergraduate Scholarships",
    provider: "Reliance Foundation",
    amount: "Up to ₹2,00,000 over course duration",
    deadline: new Date("2026-10-15"),
    states: ["All India"],
    courses: ["UG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 1500000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Class 12th Certificate", "JEE/NEET Scorecard (if applicable)", "Family Income Proof", "Aadhaar"],
    description: "Supports undergraduate students in any stream based on merit-cum-means criteria.",
    featured: true,
    tags: ["Reliance", "Corporate", "Merit-cum-Means"]
  },
  {
    title: "Adobe Women-in-Technology Scholarship",
    provider: "Adobe India",
    amount: "US $10,000 (equivalent INR) + internship",
    deadline: new Date("2026-09-30"),
    states: ["All India"],
    courses: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 1500000,
    yearLevels: ["2nd Year", "3rd Year"],
    requiredDocuments: ["Resume", "Academic Transcripts", "Recommendation Letters", "Essay Answers"],
    description: "Encourages women developers to excel in computer science and technology.",
    featured: true,
    tags: ["Adobe", "Corporate", "Girl Student"]
  },
  {
    title: "Federal Bank Hormis Memorial Foundation Scholarship",
    provider: "Federal Bank Ltd",
    amount: "100% Tuition fee reimbursement + book allowance",
    deadline: new Date("2026-11-15"),
    states: ["Kerala", "Tamil Nadu", "Karnataka", "Maharashtra", "Gujarat"],
    courses: ["UG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 300000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Admission Marksheet", "Income Proof", "Domicile Certificate", "Tuition Fee bill"],
    description: "Assists students pursuing professional courses (MBBS, Engineering, Agriculture, BSc Nursing).",
    featured: false,
    tags: ["Federal Bank", "Banking", "Professional"]
  },
  {
    title: "Axis Bank Foundation Scholarship Program",
    provider: "Axis Bank Foundation",
    amount: "₹40,000 per year",
    deadline: new Date("2026-10-05"),
    states: ["All India"],
    courses: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 300000,
    yearLevels: ["1st Year", "2nd Year"],
    requiredDocuments: ["Class 12 Marksheet", "Income Certificate", "Bank Statement", "College ID"],
    description: "Aims to facilitate access to higher education for economically disadvantaged youths.",
    featured: false,
    tags: ["Axis Bank", "Banking", "Private"]
  },

  // --- Engineering and Tech Specific ---
  {
    title: "DST INSPIRE Fellowship for Higher Education (SHE)",
    provider: "Department of Science & Technology, Govt of India",
    amount: "₹80,000 per year",
    deadline: new Date("2026-08-30"),
    states: ["All India"],
    courses: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 1200000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["INSPIRE Eligibility Note", "Board Marksheet", "Endorsement Certificate", "Aadhaar"],
    description: "Offered to meritorious students performing in top 1% of State/Central Board examinations at Class 12, pursuing Natural/Basic Sciences.",
    featured: true,
    tags: ["INSPIRE", "Science", "Government"]
  },
  {
    title: "OP Jindal Engineering and Management Scholarship (OPJEMS)",
    provider: "OP Jindal Group",
    amount: "₹80,000 to ₹1,50,000 per year",
    deadline: new Date("2026-09-20"),
    states: ["All India"],
    courses: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 1200000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year", "4th Year"],
    requiredDocuments: ["College recommendation", "Engineering/MBA CGPA report", "Aadhaar Card"],
    description: "Highly competitive scholarship given to top performers in selected engineering and management schools in India.",
    featured: false,
    tags: ["Engineering", "Management", "Private"]
  },
  {
    title: "L'Oréal India For Young Women In Science Scholarship",
    provider: "L'Oréal India",
    amount: "₹2,50,000 over course duration",
    deadline: new Date("2026-07-30"),
    states: ["All India"],
    courses: ["UG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 600000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Class 12 Marksheet (Min 85% Science)", "Income Certificate", "College Admission Slip"],
    description: "Exclusively for girl students who have passed class 12 in science stream and want to pursue graduation in science/engineering.",
    featured: true,
    tags: ["L'Oreal", "Girl Student", "Science"]
  },
  {
    title: "Fair & Lovely Foundation Scholarship",
    provider: "Hindustan Unilever Limited",
    amount: "₹25,000 to ₹50,000 per year",
    deadline: new Date("2026-10-31"),
    states: ["All India"],
    courses: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 400000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["12th Marksheet", "College Admission Proof", "Income Certificate", "Passport photo"],
    description: "Supports vocational and higher education dreams of deserving young women across India.",
    featured: false,
    tags: ["HUL", "Girl Student", "Private"]
  },
  {
    title: "Siemens Scholarship Program",
    provider: "Siemens India",
    amount: "Full tuition fee + books + mentoring",
    deadline: new Date("2026-08-31"),
    states: ["All India"],
    courses: ["UG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 200000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["First year B.Tech admission letter", "12th mark list", "Family Income proof", "Aadhar"],
    description: "Aims to support first-year engineering students from Government Engineering colleges under needy backgrounds.",
    featured: true,
    tags: ["Siemens", "Engineering", "Mentoring"]
  },
  {
    title: "Keep India Smiling Foundation Scholarship",
    provider: "Colgate-Palmolive India",
    amount: "₹30,000 per year",
    deadline: new Date("2026-09-30"),
    states: ["All India"],
    courses: ["UG", "Diploma", "10+2"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 500000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["12th Marksheet", "Income proof", "ID Card", "Fee Receipt"],
    description: "Provides foundational support to students at various stages of education to build careers.",
    featured: false,
    tags: ["Colgate", "Private", "Financial-Aid"]
  },
  {
    title: "Legrand Scholarship Program",
    provider: "Legrand India",
    amount: "60% of tuition fee or up to ₹60,000 per year",
    deadline: new Date("2026-10-15"),
    states: ["All India"],
    courses: ["UG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 500000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Class 10 & 12 marksheets", "Income certificate", "College admission proof", "Bank statements"],
    description: "Financial assistance program for female students pursuing B.Tech, BE, B.Arch, or other technical degrees.",
    featured: false,
    tags: ["Legrand", "Girl Student", "Technical"]
  },
  {
    title: "Sitaram Jindal Foundation Scholarship",
    provider: "Sitaram Jindal Foundation",
    amount: "₹1,000 to ₹3,200 per month",
    deadline: new Date("2026-12-31"),
    states: ["All India"],
    courses: ["10+2", "UG", "PG", "Diploma"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 400000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year"],
    requiredDocuments: ["Application Form", "Previous marksheets", "Income Certificate", "Bonafide Student certificate"],
    description: "Philanthropic scholarship scheme covering multiple course levels, based strictly on merit and economic eligibility.",
    featured: false,
    tags: ["Jindal", "Philanthropy", "Merit"]
  },
  {
    title: "Panasonic Ratti Chhatr Scholarship",
    provider: "Panasonic India",
    amount: "₹42,500 per year",
    deadline: new Date("2026-08-15"),
    states: ["All India"],
    courses: ["UG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 400000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["IIT JEE Rank Card", "Admission Fee Receipt", "12th Marksheet", "Income certificate"],
    description: "Specifically targets undergraduate students admitted to any of the Indian Institutes of Technology (IITs).",
    featured: true,
    tags: ["Panasonic", "IIT", "Engineering"]
  },
  {
    title: "NTPC Scholarship Scheme for SC/ST/PwD",
    provider: "National Thermal Power Corporation (NTPC)",
    amount: "₹1,500 per month",
    deadline: new Date("2026-11-30"),
    states: ["All India"],
    courses: ["UG", "PG", "Diploma"],
    categories: ["SC", "ST"],
    incomeLimit: 300000,
    yearLevels: ["2nd Year", "3rd Year", "4th Year"],
    requiredDocuments: ["Caste Certificate", "Disability Certificate (if PwD)", "Engineering/Diploma marksheets"],
    description: "Aims to help SC, ST, and physically challenged students pursuing B.Tech or Diploma courses.",
    featured: false,
    tags: ["NTPC", "SC/ST", "Government"]
  },
  {
    title: "ONGC Scholarship Scheme for Meritorious SC/ST Students",
    provider: "ONGC Foundation",
    amount: "₹48,000 per year",
    deadline: new Date("2026-10-15"),
    states: ["All India"],
    courses: ["UG", "PG"],
    categories: ["SC", "ST"],
    incomeLimit: 450000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["ONGC Application Form", "Caste Certificate", "Income certificate", "Class 12/Degree marksheet"],
    description: "Supports students enrolled in 1st year Engineering, MBBS, MBA, or Master in Geophysics/Geology.",
    featured: true,
    tags: ["ONGC", "SC/ST", "Government"]
  },
  {
    title: "ONGC Scholarship Scheme for OBC Candidates",
    provider: "ONGC Foundation",
    amount: "₹48,000 per year",
    deadline: new Date("2026-10-15"),
    states: ["All India"],
    courses: ["UG", "PG"],
    categories: ["OBC"],
    incomeLimit: 450000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["OBC Caste Certificate", "Income Certificate", "Class 12th/Graduation marksheet"],
    description: "Dedicated scholarship program for students belonging to Other Backward Classes (OBC).",
    featured: false,
    tags: ["ONGC", "OBC", "Government"]
  },
  {
    title: "GP Birla Educational Scholarship",
    provider: "GP Birla Trust",
    amount: "Up to ₹50,000 per year + laptop allowance",
    deadline: new Date("2026-08-31"),
    states: ["West Bengal"],
    courses: ["UG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 300000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Class 12th marksheet (Min 85% WB board or 90% CBSE)", "Income proof", "College admission proof"],
    description: "Supports highly meritorious students from West Bengal to complete their undergraduate studies in any stream.",
    featured: false,
    tags: ["Birla", "West Bengal", "Merit"]
  },
  {
    title: "E-Kalyan Jharkhand Post Matric Scholarship",
    provider: "Scheduled Tribe, Scheduled Caste, Minority and Welfare Dept, Govt of Jharkhand",
    amount: "Reimbursement of tuition & college fee",
    deadline: new Date("2026-11-20"),
    states: ["Jharkhand"],
    courses: ["10+2", "UG", "PG", "Diploma"],
    categories: ["SC", "ST", "OBC"],
    incomeLimit: 250000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year"],
    requiredDocuments: ["Caste Certificate", "Income Certificate", "Residential Certificate", "Bonafide Certificate"],
    description: "Assists post-matric students of SC/ST/OBC categories belonging to Jharkhand state.",
    featured: false,
    tags: ["Jharkhand", "State", "E-Kalyan"]
  },
  {
    title: "Rajasthan Post Matric Scholarship Scheme",
    provider: "Social Justice and Empowerment Department, Government of Rajasthan",
    amount: "Fee reimbursement & stipend",
    deadline: new Date("2026-11-30"),
    states: ["Rajasthan"],
    courses: ["10+2", "UG", "PG", "Diploma"],
    categories: ["SC", "ST", "OBC", "EBC"],
    incomeLimit: 250000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year"],
    requiredDocuments: ["Jan Aadhaar Card", "Caste Certificate", "Income Certificate", "Fee Receipt"],
    description: "Financial assistance for education after class 10 for backward community residents of Rajasthan.",
    featured: false,
    tags: ["Rajasthan", "State", "Social-Welfare"]
  },
  {
    title: "Medhabruti Scholarship Odisha",
    provider: "Higher Education Department, Government of Odisha",
    amount: "₹6,000 to ₹10,000 per year",
    deadline: new Date("2026-10-31"),
    states: ["Odisha"],
    courses: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 600000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Odisha Resident Proof", "Marksheet", "Income certificate", "College bonafide"],
    description: "Awards financial assistance to meritorious students of Odisha pursuing technical, professional, or general degree courses.",
    featured: false,
    tags: ["Odisha", "State", "Merit"]
  },
  {
    title: "DRDO Scholarship Scheme for Girls",
    provider: "Defence Research and Development Organisation (DRDO)",
    amount: "₹1,20,000 to ₹1,86,000 per year",
    deadline: new Date("2026-09-15"),
    states: ["All India"],
    courses: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 1200000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["JEE/GATE Scorecard", "12th/Degree Marksheet", "Admission proof", "Aadhar card"],
    description: "Supports girl students pursuing undergraduate or postgraduate courses in Aerospace/Aeronautical/Space/Rocket Engineering.",
    featured: true,
    tags: ["DRDO", "Girl Student", "Engineering"]
  },
  {
    title: "MOMA Merit Cum Means Scholarship",
    provider: "Ministry of Minority Affairs, Govt of India",
    amount: "₹20,000 to ₹30,000 per year",
    deadline: new Date("2026-10-31"),
    states: ["All India"],
    courses: ["UG", "PG"],
    categories: ["Minority"],
    incomeLimit: 250000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year", "4th Year"],
    requiredDocuments: ["Minority Declaration", "Income Certificate", "Marksheet", "Bank details"],
    description: "For minority community students pursuing professional or technical courses in registered Indian institutions.",
    featured: false,
    tags: ["NSP", "Minority", "Professional"]
  },
  {
    title: "Single Girl Child Fellowship for Single Girl Child",
    provider: "UGC - Government of India",
    amount: "₹31,000 to ₹35,000 per month",
    deadline: new Date("2026-09-30"),
    states: ["All India"],
    courses: ["PhD"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 1500000,
    yearLevels: ["1st Year", "2nd Year"],
    requiredDocuments: ["Single Girl Child Affidavit", "PhD Registration", "Marksheets", "Aadhar Card"],
    description: "Assists single girl child scholars carrying out research leading to PhD in Science or Social Sciences.",
    featured: false,
    tags: ["UGC", "PhD", "Girl Student"]
  },
  {
    title: "Post Graduate Indira Gandhi Scholarship for Single Girl Child",
    provider: "UGC - Government of India",
    amount: "₹36,200 per year for 2 years",
    deadline: new Date("2026-10-31"),
    states: ["All India"],
    courses: ["PG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 1500000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Single Girl Child Stamp Paper Affidavit", "Admission Receipt", "Degree Certificate"],
    description: "Aims to compensate direct costs of girl education in post-graduate courses where she is the only girl child in the family.",
    featured: false,
    tags: ["UGC", "PG", "Girl Student"]
  },
  {
    title: "Post Graduate Scholarship for Professional Courses for SC/ST Candidates",
    provider: "UGC - Government of India",
    amount: "₹7,800 per month (M.Tech) or ₹4,700 per month (Others)",
    deadline: new Date("2026-10-31"),
    states: ["All India"],
    courses: ["PG"],
    categories: ["SC", "ST"],
    incomeLimit: 600000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Caste Certificate", "Degree certificate", "Tuition Fee receipt", "Admission proof"],
    description: "Assists SC/ST students in undertaking postgraduate professional courses at recognized universities/colleges.",
    featured: false,
    tags: ["UGC", "PG", "SC/ST"]
  },
  {
    title: "Nalanda University Fellowship Program",
    provider: "Nalanda University",
    amount: "Full fee waiver + free accommodation + stipend",
    deadline: new Date("2026-06-30"),
    states: ["Bihar"],
    courses: ["PG", "PhD"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 1000000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Statement of Purpose", "CV", "Graduation transcript", "References"],
    description: "International study fellowship to pursue post-graduate programs in Historical Studies, Ecology, and Buddhist Studies.",
    featured: true,
    tags: ["Bihar", "Nalanda", "Fellowship"]
  },
  {
    title: "Aditya Birla Scholarship Program",
    provider: "Aditya Birla Group",
    amount: "₹65,000 to ₹1,75,000 per year",
    deadline: new Date("2026-07-15"),
    states: ["All India"],
    courses: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 1500000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Essay", "Admission letters to premier schools (IITs, IIMs, XLRI, Law schools)"],
    description: "Recognizes merit and fosters future leaders by supporting engineering, management, and law students at premier institutes.",
    featured: true,
    tags: ["Corporate", "Premier", "Elite"]
  },
  {
    title: "Muthoot M George Higher Education Scholarship",
    provider: "Muthoot M George Foundation",
    amount: "Up to ₹2,00,000 total",
    deadline: new Date("2026-09-30"),
    states: ["Kerala", "Karnataka", "Tamil Nadu", "Andhra Pradesh", "Delhi"],
    courses: ["UG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 200000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Class 12 marksheet", "College Admission document", "Income Certificate"],
    description: "Designed for students pursuing professional courses (MBBS, B.Tech, BSc Nursing) who have high marks but face financial constraint.",
    featured: false,
    tags: ["Corporate", "South India", "Financial-Aid"]
  },
  {
    title: "Schindler Igniting Minds Scholarship",
    provider: "Schindler India",
    amount: "₹20,000 one-time",
    deadline: new Date("2026-11-15"),
    states: ["All India"],
    courses: ["Diploma"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 200000,
    yearLevels: ["1st Year", "2nd Year"],
    requiredDocuments: ["Diploma Admission Letter", "10th/12th mark list", "Family Income proof"],
    description: "Supports ITI or polytechnic diploma students pursuing vocational/technical training.",
    featured: false,
    tags: ["Schindler", "Diploma", "Vocational"]
  },
  {
    title: "JK Lakshmi Vidya Scholarship",
    provider: "JK Lakshmi Cement Ltd",
    amount: "₹10,000 to ₹30,000 per year",
    deadline: new Date("2026-10-31"),
    states: ["Rajasthan", "Gujarat", "Haryana", "Madhya Pradesh", "Chhattisgarh"],
    courses: ["UG", "Diploma"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 400000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Admission confirmation", "Fee invoice", "Marks list", "Income proof"],
    description: "CSR initiative focusing on children of construction workers, small drivers, and artisans to enable higher education.",
    featured: false,
    tags: ["Corporate", "Social-Welfare", "Private"]
  },
  {
    title: "IndusInd Bank Merit-cum-Means Scholarship",
    provider: "IndusInd Bank",
    amount: "₹15,000 to ₹50,000 per year",
    deadline: new Date("2026-09-15"),
    states: ["All India"],
    courses: ["UG", "PG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 300000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["Class 12 result sheet", "Admitted College fee receipt", "Income affidavit"],
    description: "Supports students entering college streams (Commerce, Science, Arts, Engineering) with high marks and low household incomes.",
    featured: false,
    tags: ["IndusInd", "Banking", "Merit-cum-Means"]
  },
  {
    title: "Canara Bank Scholarship Scheme for SC/ST Students",
    provider: "Canara Bank",
    amount: "₹5,000 to ₹10,000 per year",
    deadline: new Date("2026-12-05"),
    states: ["All India"],
    courses: ["UG", "PG"],
    categories: ["SC", "ST"],
    incomeLimit: 250000,
    yearLevels: ["1st Year", "2nd Year", "3rd Year"],
    requiredDocuments: ["SC/ST Caste certificate", "College fee structure", "Marksheet"],
    description: "Financial assistance program by Canara Bank to encourage SC/ST students in post-matric studies.",
    featured: false,
    tags: ["Canara Bank", "Banking", "SC/ST"]
  },
  {
    title: "Santoor Scholarship Program",
    provider: "Wipro Consumer Care and Wipro Cares",
    amount: "₹24,000 per year",
    deadline: new Date("2026-08-31"),
    states: ["Karnataka", "Andhra Pradesh", "Telangana", "Chhattisgarh"],
    courses: ["UG"],
    categories: ["General", "OBC", "SC", "ST"],
    incomeLimit: 400000,
    yearLevels: ["1st Year"],
    requiredDocuments: ["10th exam card", "12th board marksheet", "Bank details", "Income declaration"],
    description: "Supports higher education of girls from disadvantaged backgrounds who wish to pursue a graduate degree program.",
    featured: true,
    tags: ["Wipro", "Girl Student", "South India"]
  }
];
